### ISSUE TITLE
Pre-trained model can not be downloaded.

### ISSUE THREAD

**Issue by TheagaoMIR** [sweetcocoa/crepe-pytorch#1]
Hi, this torch version is so great, but I can not download your pre-trained models. Is it not public?

**Comment by sweetcocoa** [comment]
Hi, Thank you for your interest.Pretrained model is public.  I'd checked that it can be accessed without login. so it is not private repo. :)it will be automatically downloaded when you first initialize the model.e. g. import crepe
import torch
device = torch.device(0)
cr = crepe.CREPE("full").to(device)or, you can download the file directly from this branch https://github.com/sweetcocoa/crepe-pytorch/tree/modelsRegards,--------- 원본 메일 ---------보낸사람 : TheaGao <notifications@github.com>받는사람 : sweetcocoa/crepe-pytorch <crepe-pytorch@noreply.github.com>참조 : Subscribed <subscribed@noreply.github.com>받은날짜 : 2020-06-04 (목) 19:15:44제목 : [sweetcocoa/crepe-pytorch] Pre-trained model can not be downloaded. (#1)
Hi, this torch version is so great, but I can not download your pre-trained models. Is it not public?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sweetcocoa/crepe-pytorch/issues/1",
"url": "https://github.com/sweetcocoa/crepe-pytorch/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by sweetcocoa** [comment]
Hi, Thank you for your interest.

Pretrained model is public.  I'd checked that it can be accessed without login. so it is not private repo. :)

it will be automatically downloaded when you first initialize the model.

e. g. 
```python
import crepe
import torch
device = torch.device(0)
cr = crepe.CREPE("full").to(device)
```

or, you can download the file directly from this branch 

[https://github.com/sweetcocoa/crepe-pytorch/tree/models](https://github.com/sweetcocoa/crepe-pytorch/tree/models)
